variable "tenancy_ocid" {}
variable "compartment_ocid" {}
variable "region" {}
variable "authorized_ips_list" {}
variable "ssh_public_key_file_websrv" {}
variable "ssh_private_key_file_websrv" {}
variable "ssh_public_key_file_bastion" {}
variable "ssh_private_key_file_bastion" {}
variable "use_cert_cs" {}
variable "file_lb_cert" {}
variable "file_ca_cert" {}
variable "file_lb_key" {}
variable "cidr_vcn" {}
variable "cidr_public_subnet" {}
variable "cidr_private_subnet" {}
variable "bastion_private_ip" {}
variable "websrv_private_ips" {}
variable "AD_bastion" {}
variable "AD_websrvs" {}
variable "BootStrapFile_websrv" {}
variable "BootStrapFile_bastion" {}
variable "verify_peer_certificate" {}
