## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_pythonapp {
  compartment_id = var.compartment_ocid
  display_name = "pythonapp"
  subnet_ids = [
    oci_core_subnet.tf-demo07c-private-subnet.id
  ]
}

resource oci_functions_function export_pythonfn {
  application_id = oci_functions_application.export_pythonapp.id
  display_name = "pythonfn"
  image              = "fra.ocir.io/wedoinfra/demofunc/pythonfn:0.0.14"
  image_digest       = "sha256:1fdcfde701008a49aee4e2e699c29d35645d9d404d7bb317375b34a74ffef0da"
  memory_in_mbs      = "256"
  timeout_in_seconds = "30"
}

