## This configuration was generated by terraform-provider-oci

resource oci_apigateway_gateway export_ai-service-gateway {
  compartment_id = var.compartment_ocid
  display_name  = "ai-service-gateway"
  endpoint_type = "PRIVATE"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  response_cache_details {
    type = "NONE"
  }
  subnet_id = oci_core_subnet.tf-demo07c-private-subnet.id
}

resource oci_apigateway_deployment export_ai-vision-service {
  compartment_id = var.compartment_ocid
  display_name = "ai-vision-service"
  gateway_id  = oci_apigateway_gateway.export_ai-service-gateway.id
  path_prefix = "/"
  specification {
    request_policies {
      mutual_tls {
        allowed_sans = [
        ]
        is_verified_certificate_required = "false"
      }
    }
    routes {
      backend {
        function_id = oci_functions_function.export_pythonfn.id
        type = "ORACLE_FUNCTIONS_BACKEND"
      }
      methods = [
        "POST",
      ]
      path = "/analize-image"
    }
  }
}

