## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_pythonapp {
  compartment_id = var.compartment_ocid
  display_name = "pythonapp"
  subnet_ids = [
    oci_core_subnet.tf-demo07c-private-subnet.id
  ]
}

resource oci_functions_function export_pythonfn {
  depends_on = [null_resource.function_Push2OCIR]
  application_id = oci_functions_application.export_pythonapp.id
  display_name = "pythonfn"
  image = "${local.ocir_docker_repository}/${local.ocir_namespace}/${var.ocir_repo_name}/ai-vision-func:0.0.1"
  memory_in_mbs      = "256"
  config = { 
      "REGION" : "${var.region}"
    }
  timeout_in_seconds = "30"
}
