CREATE TABLE ITEM_DETAILS (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (CACHE 5) PRIMARY KEY,
  doc CLOB CONSTRAINT valid_json CHECK (doc IS JSON));


INSERT INTO ITEM_DETAILS (doc) VALUES (
'{
  "id" : "Eiffel_Tower",
  "name" : "Eiffel Tower",
  "description": "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower. "
}'
);
INSERT INTO ITEM_DETAILS (doc) VALUES (
'{
  "id" : "Stonehenge",
  "name" : "Stonehenge",
  "description": "Stonehenge is a prehistoric monument on Salisbury Plain in Wiltshire, England, two miles (3 km) west of Amesbury. It consists of an outer ring of vertical sarsen standing stones, each around 13 feet (4.0 m) high, seven feet (2.1 m) wide, and weighing around 25 tons, topped by connecting horizontal lintel stones."
}'
);

commit;